name: Frontend CI 

on:
  push:
    branches: [staging,main]
  pull_request:
    branches: [staging,main]
jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout your code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Install Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Run lint
      - name: Run lint
        run: npm run lint

      # 5️⃣ Run tests
      - name: Run tests
        run: npm test -- --watch=false
        env:
          CI: true

      # 6️⃣ Build production version
      - name: Build app
        run: npm run build
